config/routes.rb
# == Route Map
#
#               Prefix Verb   URI Pattern                      Controller#Action
#                 root GET    /                                pages#index
#     new_user_session GET    /users/sign_in(.:format)         devise/sessions#new
#         user_session POST   /users/sign_in(.:format)         devise/sessions#create
# destroy_user_session DELETE /users/sign_out(.:format)        devise/sessions#destroy
#        user_password POST   /users/password(.:format)        devise/passwords#create
#    new_user_password GET    /users/password/new(.:format)    devise/passwords#new
#   edit_user_password GET    /users/password/edit(.:format)   devise/passwords#edit
#                      PATCH  /users/password(.:format)        devise/passwords#update
#                      PUT    /users/password(.:format)        devise/passwords#update
#                 user GET    /users/:id(.:format)             users#show
#            contracts GET    /contracts(.:format)             contracts#index
#                      POST   /contracts(.:format)             contracts#create
#         new_contract GET    /contracts/new(.:format)         contracts#new
#              clients GET    /clients(.:format)               clients#index
#                      POST   /clients(.:format)               clients#create
#           new_client GET    /clients/new(.:format)           clients#new
#          engagements GET    /engagements(.:format)           engagements#index
#                      POST   /engagements(.:format)           engagements#create
#       new_engagement GET    /engagements/new(.:format)       engagements#new
#              vendors GET    /vendors(.:format)               vendors#index
#                      POST   /vendors(.:format)               vendors#create
#           new_vendor GET    /vendors/new(.:format)           vendors#new
#      financial_years GET    /financial_years(.:format)       financial_years#index
#                      POST   /financial_years(.:format)       financial_years#create
#   new_financial_year GET    /financial_years/new(.:format)   financial_years#new
#    advertising_types GET    /advertising_types(.:format)     advertising_types#index
#                      POST   /advertising_types(.:format)     advertising_types#create
# new_advertising_type GET    /advertising_types/new(.:format) advertising_types#new
#       campaign_types GET    /campaign_types(.:format)        campaign_types#index
#                      POST   /campaign_types(.:format)        campaign_types#create
#    new_campaign_type GET    /campaign_types/new(.:format)    campaign_types#new
#          media_types GET    /media_types(.:format)           media_types#index
#                      POST   /media_types(.:format)           media_types#create
#       new_media_type GET    /media_types/new(.:format)       media_types#new
#          experiments GET    /experiments(.:format)           pages#experiments
#

Rails.application.routes.draw do
  root 'pages#index'

  devise_for :users
  resources :users, only: [:show]

  resources :contracts,       only: [:index, :new, :create]
  
  resources :clients,         only: [:index, :new, :create]
  resources :engagements,     only: [:index, :new, :create]
  resources :vendors,         only: [:index, :new, :create]
  resources :financial_years, only: [:index, :new, :create]

  resources :advertising_types, only: [:index, :new, :create]
  resources :campaign_types,    only: [:index, :new, :create]
  resources :media_types,       only: [:index, :new, :create]

  get 'experiments' => 'pages#experiments'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/shared/_footer.html.haml
%footer
  #modals
    #quick-add-client
    #quick-add-engagement
    #quick-add-vendor
    #quick-add-advertising-type
    #quick-add-campaign-type
    #quick-add-media-type
    #quick-add-financial-year

app/views/shared/_navbar_top.html.haml
.container-fluid
  .navbar-header
    %button.navbar-toggle{'data-target' => '.navbar-collapse', 'data-toggle' => 'collapse', type: 'button'}
      %span.fa.fa-gear
    %a.navbar-brand{href: '#'}
      %span MediaPlanning
  .navbar-collapse.collapse
    %ul.nav.navbar-nav
      %li
        = link_to 'Home', user_path(current_user)
      %li
        %a{href: '#'} Support
      %li.dropdown
        %a.dropdown-toggle#quick-add{'data-toggle' => 'dropdown', href: '#'}
          %i.fa.fa-plus-square
          Quick Add
          %b.caret
        %ul.dropdown-menu.col-menu-2
          %li.col-sm-6.no-padding
            %ul
              %li.dropdown-header
                %i.fa.fa-file-text-o>
                Contracts
              %li
                = link_to 'New Contract', new_contract_path
              %li.dropdown-header
                %i.fa.fa-ticket>
                Tickets
              %li
                %a{href: '#'} New Ticket Data
            %ul
              %li.dropdown-header
                %i.fa.fa-database>
                Entities
              %li
                = link_to 'New Client', new_client_path, remote: true
              %li
                = link_to 'New Engagement', new_engagement_path, remote: true
              %li
                = link_to 'New Vendor', new_vendor_path, remote: true
          %li.col-sm-6.no-padding
            %ul
              %li.dropdown-header
                %i.fa.fa-building-o>
                Organization
              %li
                = link_to 'New Financial Year', new_financial_year_path, remote: true
            %ul
              %li.dropdown-header
                %i.fa.fa-list-ul>
                System Types
              %li
                = link_to 'New Advertising Type', new_advertising_type_path, remote: true
              %li
                = link_to 'New Campaign Type', new_campaign_type_path, remote: true
              %li
                = link_to 'New Media Type', new_media_type_path, remote: true
    %ul.nav.navbar-nav.navbar-right.user-nav
      %li.dropdown.profile_menu
        %a.dropdown-toggle{'data-toggle' => 'dropdown', href: '#'}
          %span
            = current_user.name
          %b.caret
        %ul.dropdown-menu
          / %li
          /   %a{href: '#'} My Account
          / %li.divider
          %li
            = link_to('Sign Out', destroy_user_session_path, :method => :delete)

app/views/shared/_notice.html.haml
= bootstrap_flash

:javascript
  $(document).ready( function() {
    $(".alert-success").delay(2000).fadeTo('slow', 0.0, function () { $(this).remove(); });
    $(".alert-info").delay(8000).fadeTo('slow',    0.0, function () { $(this).remove(); });
    // $(".alert-warning").delay(8000).fadeTo('slow', 0.0, function () { $(this).remove(); });
    // $(".alert-danger").delay(8000).fadeTo('slow',  0.0, function () { $(this).remove(); });
  } );

app/views/shared/_sidebar.html.haml
.cl-sidebar{"data-intro" => "Fixed Sidebar... It adjust to your needs.", "data-position" => "right", "data-step" => "1"}
  .cl-toggle
    %i.fa.fa-bars
  .cl-navblock
    .menu-space
      .content
        %ul.cl-vnavigation
          %li
            %a{href: '#'}
              %i.fa.fa-home
              %span Dashboards
            %ul.sub-menu
              %li.active#home
                = link_to 'Home', user_path(current_user)
          %li
            %a{href: '#'}
              %i.fa.fa-bar-chart-o
              %span Reporting
            %ul.sub-menu
              %li#report
                = link_to 'Coming soon...', '#'
          %li
            %a{href: '#'}
              %i.fa.fa-file-text-o
              %span Contracts
            %ul.sub-menu
              %li#contracts
                = link_to 'Show Contracts', contracts_path
              %li#addcontract
                = link_to 'Add New Contract', new_contract_path
          %li
            %a{href: '#'}
              %i.fa.fa-ticket
              %span Tickets
            %ul.sub-menu
              %li#tickets
                = link_to 'Show Tickets', '#'
          %li
            %a{href: '#'}
              %i.fa.fa-users
              %span Clients
            %ul.sub-menu
              %li#clients
                = link_to 'Show Clients', clients_path
          %li
            %a{href: '#'}
              %i.fa.fa-film
              %span Engagements
            %ul.sub-menu
              %li#engagements
                = link_to 'Show Engagements', engagements_path
          %li
            %a{href: '#'}
              %i.fa.fa-bullhorn
              %span Vendors
            %ul.sub-menu
              %li#vendors
                = link_to 'Show Vendors', vendors_path
          %li
            %a{href: '#'}
              %i.fa.fa-building-o
              %span Organization
            %ul.sub-menu
              %li#financialyears
                = link_to 'Financial Years', financial_years_path
          %li
            %a{href: '#'}
              %i.fa.fa-list-ul
              %span System Types
            %ul.sub-menu
              %li#advertisings
                = link_to 'Advertising Types', advertising_types_path
              %li#campaigns
                = link_to 'Campaign Types', campaign_types_path
              %li#medias
                = link_to 'Media Types', media_types_path
          %li
            %a{href: '#'}
              %i.fa.fa-user
              %span User Accounts
            %ul.sub-menu
              %li#users
                = link_to 'Coming soon...', '#'
    -#.text-right.collapse-button{style: "padding:7px 9px;"}
    -#  %input.form-control.search{placeholder: "Search...", type: "text"}/
    -#  %button#sidebar-collapse.btn.btn-default{style: ""}
    -#    %i.fa.fa-angle-left{style: "color:#fff;"}